/** Build src/catalog.generated.ts from upstream libraries.json (232 entries).
 *  Usage: node scripts/build-catalog.mjs [libraries.json|URL] [out]
 *  Defaults to fetching upstream; pass a local path for offline refresh.
 *  Curated overrides (keywords/samples for top picks) live below and win on slug match.
 */
import { readFile, writeFile } from "node:fs/promises";

const UPSTREAM = "https://raw.githubusercontent.com/excalidraw/excalidraw-libs/main/libraries.json";
const [indexSrc = UPSTREAM, outPath = "src/catalog.generated.ts"] = process.argv.slice(2);

/** Hand-tuned overrides: slug -> { keywords, sampleItems }. */
const OVERRIDES = {
  "aws-serverless-icons-v2": {
    keywords: "aws lambda serverless cloud s3 dynamodb api gateway sqs sns",
    sampleItems: ["Lambda", "APIGateway", "DynamoDB", "SQS", "SNS"],
  },
  "network-topology-icons": {
    keywords: "network router switch firewall server vpn topology",
    sampleItems: ["Router", "Switch", "Firewall", "Server", "VPN"],
  },
  "dev-ops": {
    keywords: "devops ansible vault consul nomad github docker kubernetes terraform",
    sampleItems: ["Docker", "Kubernetes", "Terraform", "Ansible"],
  },
  "uml-er-library": {
    keywords: "uml er diagram class entity",
    sampleItems: ["class", "entity"],
  },
  "awesome-icons": {
    keywords: "icon user lock search chart email calendar home ui",
    sampleItems: ["User", "Lock", "Search", "Chart", "email"],
  },
  "system-icons": {
    keywords: "icon document cloud file star system",
    sampleItems: ["document", "cloud", "star"],
  },
  "systemdesignicons": {
    keywords: "system design cache cluster mapreduce",
    sampleItems: ["ServiceCluster", "cacheLayer"],
  },
};

/** Local filenames shipped in npm (offline). */
const BUNDLED = new Set([
  "UML-ER-library.excalidrawlib",
  "awesome-icons.excalidrawlib",
  "dev_ops.excalidrawlib",
  "network-topology-icons.excalidrawlib",
  "system-icons.excalidrawlib",
  "systemdesignicons.excalidrawlib",
]);

const STOP = new Set("and or the for with from icons icon library diagrams diagram set of a an to in on".split(" "));

function slugify(s) {
  return s.toLowerCase().replace(/\.excalidrawlib$/, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function keywordsOf(name, description) {
  const toks = `${name} ${description}`.toLowerCase().split(/[^a-z0-9+#]+/).filter((t) => t && !STOP.has(t) && t.length > 1);
  return [...new Set(toks)].join(" ");
}

const raw = indexSrc.startsWith("http")
  ? await (await fetch(indexSrc)).json()
  : JSON.parse(await readFile(indexSrc, "utf8"));
const used = new Map();
const entries = raw.map((e) => {
  const file = e.source.split("/").pop();
  let slug = slugify(file);
  if (used.has(slug)) slug = `${slug}-${slugify(e.source.split("/")[0])}`;
  used.set(slug, true);
  const ov = OVERRIDES[slug] ?? {};
  const itemNames = Array.isArray(e.itemNames) ? e.itemNames : [];
  return {
    slug,
    name: e.name,
    description: e.description ?? "",
    keywords: ov.keywords ?? keywordsOf(e.name, e.description ?? ""),
    source: e.source,
    file,
    sampleItems: ov.sampleItems ?? itemNames.slice(0, 5),
    bundled: BUNDLED.has(file),
    ...(itemNames.length ? { itemNames } : {}),
  };
});

const header = `/** GENERATED by scripts/build-catalog.mjs — do not hand-edit. Refresh: node scripts/build-catalog.mjs. */
import type { CatalogEntry } from "./library.js";

export const CATALOG: CatalogEntry[] = `;
await writeFile(outPath, header + JSON.stringify(entries, null, 2) + "\n");
console.log(`wrote ${entries.length} entries -> ${outPath}`);
